# Generated by Django 5.0.6 on 2024-06-17 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jiji', '0005_rename_product_cart_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
