# Generated by Django 5.0.6 on 2024-06-21 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jiji', '0006_category_image_product_image'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cart',
            table='cart',
        ),
        migrations.AlterModelTable(
            name='category',
            table='categories',
        ),
        migrations.AlterModelTable(
            name='product',
            table='products',
        ),
        migrations.AlterModelTable(
            name='region',
            table='regions',
        ),
    ]
