# Generated by Django 5.0.6 on 2024-06-21 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jiji', '0007_alter_cart_table_alter_category_table_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='region_id',
            new_name='region',
        ),
    ]
